export const format_expense = [
  {
    id: '0',
    nameCol: 'Số lượng bán',
    T1: 'meow',
    T2: 'meow',
    T3: 'meow',
    T4: 'meow',
    T5: 'meow',
    T6: 'meow',
    T7: 'meow',
    T8: 'meow',
    T9: 'meow',
    T10: 'meow',
    T11: 'meow',
    T12: 'meow',
    subRows: [
      {
        id: '0',
        nameCol: 'Áo khoác',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Túi',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      }
    ]
  },
  {
    id: '0',
    nameCol: 'Đơn giá bán',
    T1: 'meow',
    T2: 'meow',
    T3: 'meow',
    T4: 'meow',
    T5: 'meow',
    T6: 'meow',
    T7: 'meow',
    T8: 'meow',
    T9: 'meow',
    T10: 'meow',
    T11: 'meow',
    T12: 'meow',
    subRows: [
      {
        id: '0',
        nameCol: 'Áo khoác',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Túi',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      }
    ]
  },
  {
    id: '0',
    nameCol: 'Kế hoạch',
    T1: 'meow',
    T2: 'meow',
    T3: 'meow',
    T4: 'meow',
    T5: 'meow',
    T6: 'meow',
    T7: 'meow',
    T8: 'meow',
    T9: 'meow',
    T10: 'meow',
    T11: 'meow',
    T12: 'meow',
    subRows: [
      {
        id: '0',
        nameCol: 'Áo khoác',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Túi',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      }
    ]
  },
  {
    id: '0',
    nameCol: 'Doanh thu = SL*ĐG',
    T1: 'meow',
    T2: 'meow',
    T3: 'meow',
    T4: 'meow',
    T5: 'meow',
    T6: 'meow',
    T7: 'meow',
    T8: 'meow',
    T9: 'meow',
    T10: 'meow',
    T11: 'meow',
    T12: 'meow',
    subRows: [
      {
        id: '0',
        nameCol: 'Áo khoác',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Túi',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      }
    ]
  },
  {
    id: '0',
    nameCol: 'Đơn giá vốn',
    T1: 'meow',
    T2: 'meow',
    T3: 'meow',
    T4: 'meow',
    T5: 'meow',
    T6: 'meow',
    T7: 'meow',
    T8: 'meow',
    T9: 'meow',
    T10: 'meow',
    T11: 'meow',
    T12: 'meow',
    subRows: [
      {
        id: '0',
        nameCol: 'Áo khoác',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Túi',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      }
    ]
  },
  {
    id: '0',
    nameCol: 'Lợi nhuận gộp',
    T1: 'meow',
    T2: 'meow',
    T3: 'meow',
    T4: 'meow',
    T5: 'meow',
    T6: 'meow',
    T7: 'meow',
    T8: 'meow',
    T9: 'meow',
    T10: 'meow',
    T11: 'meow',
    T12: 'meow',
    subRows: [
      {
        id: '0',
        nameCol: 'Áo khoác',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Túi',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      }
    ]
  },
  {
    id: '0',
    nameCol: 'Chi phí bán hàng',
    T1: 'meow',
    T2: 'meow',
    T3: 'meow',
    T4: 'meow',
    T5: 'meow',
    T6: 'meow',
    T7: 'meow',
    T8: 'meow',
    T9: 'meow',
    T10: 'meow',
    T11: 'meow',
    T12: 'meow',
    subRows: [
      {
        id: '0',
        nameCol: 'Lương NV',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Bao bì, đóng gói',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Máy in',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Giấy in đơn',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Marketing',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Tên miền',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Hosting',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Giấy phép kinh doanh',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      },
      {
        id: '0',
        nameCol: 'Chi phí khác (Vận chuyển, phí sàn,…)',
        T1: 'meow',
        T2: 'meow',
        T3: 'meow',
        T4: 'meow',
        T5: 'meow',
        T6: 'meow',
        T7: 'meow',
        T8: 'meow',
        T9: 'meow',
        T10: 'meow',
        T11: 'meow',
        T12: 'meow'
      }
    ]
  }
]
